{
 "title": "BE tech comparison",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Test endpoint hits per minute",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "delta(count_getDummy_invocations_total{job=\"sample-quarkus-native-be\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(count_getDummy_invocations_total{job=\"sample-quarkus-be\"}[1m])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "delta(count_getDummy_invocations_total{job=\"sample-spring-native-be\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(count_getDummy_invocations_total{job=\"sample-spring-be\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "delta(get_dummy_invocations_total{job=\"sample-nestjs-be\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CPU usage (last 5 minutes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(process_cpu_usage{instance=\"sample-quarkus-native-be:8082\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(avg_over_time(process_cpu_usage{instance=\"sample-quarkus-be:8081\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(avg_over_time(process_cpu_usage{instance=\"sample-spring-native-be:8083\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(avg_over_time(process_cpu_usage{instance=\"sample-spring-be:8080\"}[5m])) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"sample-nestjs-be\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average memory used (last 5 minutes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (avg_over_time(jvm_memory_used_bytes{job=\"sample-quarkus-native-be\"}[5m])) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (avg_over_time(jvm_memory_used_bytes{job=\"sample-quarkus-be\"}[5m])) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (avg_over_time(jvm_memory_used_bytes{job=\"sample-spring-native-be\"}[5m])) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (avg_over_time(jvm_memory_used_bytes{job=\"sample-spring-be\"}[5m])) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (avg_over_time(process_resident_memory_bytes{job=\"sample-nestjs-be\"}[5m])) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "avg(process_cpu_usage{instance=\"sample-quarkus-native-be:8082\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(process_cpu_usage{instance=\"sample-quarkus-be:8081\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(process_cpu_usage{instance=\"sample-spring-be:8080\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(process_cpu_usage{instance=\"sample-spring-native-be:8083\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM memory used (MB)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by(job) (jvm_memory_used_bytes{job=\"sample-quarkus-native-be\"}) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (jvm_memory_used_bytes{job=\"sample-quarkus-be\"}) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (jvm_memory_used_bytes{job=\"sample-spring-be\"}) / 1048576",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(job) (jvm_memory_used_bytes{job=\"sample-spring-native-be\"}) / 1048576",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}