FROM maven:3.9-amazoncorretto-17-alpine AS build
COPY . .
RUN mvn clean package -P !with-code-analysis -P with-observability -P mariadb -D skipTests=true

FROM registry.access.redhat.com/ubi9/openjdk-17 AS run

ENV LANGUAGE='en_US:en'


# We make four distinct layers so if there are application changes the library layers can be re-used
COPY --from=build --chown=185 sample-quarkus-be-application/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build --chown=185 sample-quarkus-be-application/target/quarkus-app/*.jar /deployments/
COPY --from=build --chown=185 sample-quarkus-be-application/target/quarkus-app/app/ /deployments/app/
COPY --from=build --chown=185 sample-quarkus-be-application/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]

