scrape_configs:
  - job_name: 'sample-spring-be'
    scrape_interval: 10s
    metrics_path: /sample-backend/actuator/prometheus
    static_configs:
      - targets: ['sample-spring-be:8080']
  - job_name: 'sample-quarkus-be'
    scrape_interval: 10s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['sample-quarkus-be:8081']
  - job_name: 'sample-quarkus-native-be'
    scrape_interval: 10s
    metrics_path: /q/metrics
    static_configs:
      - targets: ['sample-quarkus-native-be:8082']
  - job_name: 'sample-spring-native-be'
    scrape_interval: 10s
    metrics_path: /sample-backend/actuator/prometheus
    static_configs:
      - targets: ['sample-spring-native-be:8083']
